- title: Composition
  image: images/composition.svg
  description: Thoughtfully and skillfully crafted pieces. Emotionally tailored. Unique and memorable.

- title: Production
  image: images/production.svg
  description: Polished and balanced sound. Identifiable branding. For any type of media.

- title: More
  image: images/more.svg
  description: Sound design, arranging, mixing, consulting, direction. Drum set and percussion.
